fs.makeDir("/startup")
fs.makeDir("/termUtils")
shell.run("wget https://raw.githubusercontent.com/Diebeck/CCTweaked-Program-Stash/refs/heads/main/Utility/termUtils/tree.lua /termUtils/tree.lua")
shell.run("wget https://raw.githubusercontent.com/Diebeck/CCTweaked-Program-Stash/refs/heads/main/Utility/termUtils/find.lua /termUtils/find.lua")
shell.run("wget https://raw.githubusercontent.com/Diebeck/CCTweaked-Program-Stash/refs/heads/main/Utility/termUtils/palette.lua /termUtils/palette.lua")
shell.run("wget https://raw.githubusercontent.com/Diebeck/CCTweaked-Program-Stash/refs/heads/main/Utility/termUtils/addTermUtils.lua /startup/addTermUtils.lua")
shell.run("/startup/addTermUtils.lua")